export type SiteTextInputType = "text" | "textarea";

export type SiteTextDefinition = {
  key: string;
  label: string;
  groupName: string;
  defaultValue: string;
  description: string;
  inputType: SiteTextInputType;
  hiddenInBulkEditor?: boolean;
  isPublic: boolean;
};

export const siteTextDefinitions = [
  {
    key: "homepage_announcement_eyebrow",
    label: "Ana Sayfa Duyuru Üst Yazı",
    groupName: "Duyuru",
    defaultValue: "Yeni Şarkım Çıktı",
    description: "Ana sayfa duyuru kartındaki küçük üst yazı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "homepage_announcement_title",
    label: "Ana Sayfa Duyuru Başlık",
    groupName: "Duyuru",
    defaultValue: "Zef Cara yayında.",
    description: "Ana sayfa duyuru kartındaki ana başlık.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "homepage_announcement_description",
    label: "Ana Sayfa Duyuru Açıklama",
    groupName: "Duyuru",
    defaultValue: "Spotify ve Apple Music’te dinleyebilirsin.",
    description: "Ana sayfa duyuru kartındaki açıklama.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "homepage_announcement_target_type",
    label: "Ana Sayfa Duyuru Tipi",
    groupName: "Duyuru",
    defaultValue: "song",
    description: "Duyuru hedef tipi: song, cover, photo veya link.",
    inputType: "text",
    hiddenInBulkEditor: true,
    isPublic: true,
  },
  {
    key: "homepage_announcement_target_id",
    label: "Ana Sayfa Duyuru Hedef ID",
    groupName: "Duyuru",
    defaultValue: "",
    description: "Seçilen şarkı, cover veya fotoğraf kaydının id değeri.",
    inputType: "text",
    hiddenInBulkEditor: true,
    isPublic: true,
  },
  {
    key: "homepage_announcement_target_url",
    label: "Ana Sayfa Duyuru Hedef Link",
    groupName: "Duyuru",
    defaultValue: "/sarkilarim/zef-cara",
    description: "Duyuru kartındaki Detaya Git butonunun hedefi.",
    inputType: "text",
    hiddenInBulkEditor: true,
    isPublic: true,
  },
  {
    key: "homepage_announcement_is_active",
    label: "Ana Sayfa Duyuru Aktif",
    groupName: "Duyuru",
    defaultValue: "true",
    description: "Duyuru aktifse true, pasifse false.",
    inputType: "text",
    hiddenInBulkEditor: true,
    isPublic: true,
  },
  {
    key: "homepage.cover_section_title",
    label: "Ana Sayfa Cover Bölüm Başlığı",
    groupName: "Ana Sayfa",
    defaultValue: "Coverlarım",
    description: "Ana sayfada cover vitrin bölümünün başlığı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "homepage.cover_all_button",
    label: "Ana Sayfa Tüm Coverlar Butonu",
    groupName: "Ana Sayfa",
    defaultValue: "Tüm Coverlar",
    description: "Ana sayfadaki tüm coverlar buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "homepage.song_section_title",
    label: "Ana Sayfa Şarkı Bölüm Başlığı",
    groupName: "Ana Sayfa",
    defaultValue: "Şarkılarım",
    description: "Ana sayfada şarkı vitrin bölümünün başlığı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "homepage.song_all_button",
    label: "Ana Sayfa Tüm Şarkılar Butonu",
    groupName: "Ana Sayfa",
    defaultValue: "Tüm Şarkılar",
    description: "Ana sayfadaki tüm şarkılar buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "homepage.photo_section_title",
    label: "Ana Sayfa Fotoğraf Bölüm Başlığı",
    groupName: "Ana Sayfa",
    defaultValue: "Fotoğraflarım",
    description: "Ana sayfada fotoğraf vitrin bölümünün başlığı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "homepage.photo_all_button",
    label: "Ana Sayfa Tüm Fotoğraflar Butonu",
    groupName: "Ana Sayfa",
    defaultValue: "Tüm Fotoğraflar",
    description: "Ana sayfadaki tüm fotoğraflar buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "contact.email",
    label: "İletişim E-posta",
    groupName: "İletişim",
    defaultValue: "muhammedtnklc@gmail.com",
    description: "İletişim sayfasında ve ana sayfadaki iletişim bölümünde görünen e-posta.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "contact.button.menu",
    label: "İletişim Menü Butonu",
    groupName: "İletişim",
    defaultValue: "← Menü",
    description: "İletişim alanındaki menü buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "contact.button.mail",
    label: "İletişim Mail Butonu",
    groupName: "İletişim",
    defaultValue: "Mail At",
    description: "İletişim alanındaki mail buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "contact.button.songs",
    label: "İletişim Şarkılar Butonu",
    groupName: "İletişim",
    defaultValue: "Şarkılar →",
    description: "İletişim alanındaki şarkılar buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "contact.point_1",
    label: "İletişim Bilgi Kartı 1",
    groupName: "İletişim",
    defaultValue: "Kürtçe şarkılarımı, bestelerimi ve yorumlarımı paylaşıyorum.",
    description: "İletişim bölümündeki birinci açıklama kartı.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "contact.point_2",
    label: "İletişim Bilgi Kartı 2",
    groupName: "İletişim",
    defaultValue: "Resmi yayınlarım Spotify ve Apple Music’te yer alıyor.",
    description: "İletişim bölümündeki ikinci açıklama kartı.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "contact.point_3",
    label: "İletişim Bilgi Kartı 3",
    groupName: "İletişim",
    defaultValue: "Yayın, video, görsel ve iş birliği için bana yazabilirsin.",
    description: "İletişim bölümündeki üçüncü açıklama kartı.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.badge_1",
    label: "Hakkında Rozet 1",
    groupName: "Hakkında",
    defaultValue: "Bağımsız Sanatçı",
    description: "Hakkında sayfasındaki birinci rozet.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.badge_2",
    label: "Hakkında Rozet 2",
    groupName: "Hakkında",
    defaultValue: "Kürtçe Müzik",
    description: "Hakkında sayfasındaki ikinci rozet.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.badge_3",
    label: "Hakkında Rozet 3",
    groupName: "Hakkında",
    defaultValue: "Akustik Yorum",
    description: "Hakkında sayfasındaki üçüncü rozet.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.eyebrow",
    label: "Hakkında Üst Yazı",
    groupName: "Hakkında",
    defaultValue: "Hakkında",
    description: "Hakkında sayfasındaki küçük üst yazı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.hero_title",
    label: "Hakkında Ana Başlık",
    groupName: "Hakkında",
    defaultValue: "Müziğimi Kürtçe sözler, sade melodiler ve kişisel hikâyeler üzerine kuruyorum.",
    description: "Hakkında sayfasındaki ana başlık.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.hero_description",
    label: "Hakkında Ana Açıklama",
    groupName: "Hakkında",
    defaultValue: "Kendi bestelerimde anlamlı sözleri, doğal bir yorumla ve kulağa hoş gelen modern bir akustik atmosferle birleştirmeye çalışıyorum. Cover yorumlarımda ise sevdiğim eserleri kendi sesimle, sade ve içten bir yorumla paylaşıyorum.",
    description: "Hakkında sayfasındaki ana açıklama.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.primary_button",
    label: "Hakkında Birinci Buton",
    groupName: "Hakkında",
    defaultValue: "Bestelerim",
    description: "Hakkında sayfasındaki birinci buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.secondary_button",
    label: "Hakkında İkinci Buton",
    groupName: "Hakkında",
    defaultValue: "Coverlarım",
    description: "Hakkında sayfasındaki ikinci buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.card_1_eyebrow",
    label: "Hakkında Kart 1 Üst Yazı",
    groupName: "Hakkında",
    defaultValue: "Bestelerim",
    description: "Hakkında alt kart 1 küçük üst yazı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.card_1_title",
    label: "Hakkında Kart 1 Başlık",
    groupName: "Hakkında",
    defaultValue: "Resmi yayınlarım",
    description: "Hakkında alt kart 1 başlık.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.card_1_description",
    label: "Hakkında Kart 1 Açıklama",
    groupName: "Hakkında",
    defaultValue: "Kendi yazdığım ve bestelediğim şarkılarımı Spotify ve Apple Music gibi dijital platformlarda yayınlıyorum.",
    description: "Hakkında alt kart 1 açıklama.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.card_1_button",
    label: "Hakkında Kart 1 Buton",
    groupName: "Hakkında",
    defaultValue: "Şarkılarım",
    description: "Hakkında alt kart 1 buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.card_2_eyebrow",
    label: "Hakkında Kart 2 Üst Yazı",
    groupName: "Hakkında",
    defaultValue: "Coverlarım",
    description: "Hakkında alt kart 2 küçük üst yazı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.card_2_title",
    label: "Hakkında Kart 2 Başlık",
    groupName: "Hakkında",
    defaultValue: "Yorum videolarım",
    description: "Hakkında alt kart 2 başlık.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.card_2_description",
    label: "Hakkında Kart 2 Açıklama",
    groupName: "Hakkında",
    defaultValue: "Sevdiğim eserleri kendi sesimle, sade ve içten bir yorumla YouTube ve Instagram odaklı paylaşıyorum.",
    description: "Hakkında alt kart 2 açıklama.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.card_2_button",
    label: "Hakkında Kart 2 Buton",
    groupName: "Hakkında",
    defaultValue: "Coverlarım",
    description: "Hakkında alt kart 2 buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "about.bottom_note",
    label: "Hakkında Alt Not",
    groupName: "Hakkında",
    defaultValue: "Bu sitede resmi yayınlarımı, cover yorumlarımı, fotoğraflarımı ve müzik yolculuğuma dair notları bir araya getiriyorum.",
    description: "Hakkında sayfasındaki alt açıklama notu.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.eyebrow",
    label: "Giriş Üst Yazı",
    groupName: "Giriş ve Üyelik",
    defaultValue: "Üyelik Alanı",
    description: "Giriş sayfasındaki küçük üst yazı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.title_line_1",
    label: "Giriş Başlık Satır 1",
    groupName: "Giriş ve Üyelik",
    defaultValue: "Şarkı sözleri ve özel içerikler için",
    description: "Giriş sayfası başlık ilk satır.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.title_line_2",
    label: "Giriş Başlık Satır 2",
    groupName: "Giriş ve Üyelik",
    defaultValue: "Giriş Yap veya Hesap Aç.",
    description: "Giriş sayfası başlık ikinci satır.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.forgot_password_link",
    label: "Giriş Şifremi Unuttum Linki",
    groupName: "Giriş ve Üyelik",
    defaultValue: "Şifremi unuttum",
    description: "Giriş sayfasındaki şifremi unuttum link yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.form.email_label",
    label: "Giriş Form E-posta Etiketi",
    groupName: "Giriş ve Üyelik",
    defaultValue: "E-postan",
    description: "Giriş formundaki e-posta etiketi.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.form.email_placeholder",
    label: "Giriş Form E-posta Placeholder",
    groupName: "Giriş ve Üyelik",
    defaultValue: "ornek@mail.com",
    description: "Giriş formundaki e-posta örnek metni.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.form.password_label",
    label: "Giriş Form Şifre Etiketi",
    groupName: "Giriş ve Üyelik",
    defaultValue: "Şifren",
    description: "Giriş formundaki şifre etiketi.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.form.password_placeholder",
    label: "Giriş Form Şifre Placeholder",
    groupName: "Giriş ve Üyelik",
    defaultValue: "Şifreni yaz",
    description: "Giriş formundaki şifre örnek metni.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.form.error",
    label: "Giriş Form Hata Mesajı",
    groupName: "Giriş ve Üyelik",
    defaultValue: "Bu mail ile giriş yapılamadı. Hesabın yoksa kayıt ol.",
    description: "Giriş başarısız mesajı.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.form.success",
    label: "Giriş Form Başarı Mesajı",
    groupName: "Giriş ve Üyelik",
    defaultValue: "Giriş başarılı. Hesabına yönlendiriliyorsun.",
    description: "Giriş başarılı mesajı.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.button.songs",
    label: "Giriş Form Şarkılar Butonu",
    groupName: "Giriş ve Üyelik",
    defaultValue: "← Şarkılar",
    description: "Giriş formu sol buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.button.submit",
    label: "Giriş Form Submit Butonu",
    groupName: "Giriş ve Üyelik",
    defaultValue: "Giriş Yap",
    description: "Giriş formu submit buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "login.button.covers",
    label: "Giriş Form Coverlar Butonu",
    groupName: "Giriş ve Üyelik",
    defaultValue: "Coverlar →",
    description: "Giriş formu sağ buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.eyebrow",
    label: "Şifremi Unuttum Üst Yazı",
    groupName: "Şifremi Unuttum",
    defaultValue: "Üyelik Alanı",
    description: "Şifremi unuttum sayfasındaki küçük üst yazı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.title_line_1",
    label: "Şifremi Unuttum Başlık Satır 1",
    groupName: "Şifremi Unuttum",
    defaultValue: "Hesabına tekrar erişmek için",
    description: "Şifremi unuttum başlık satır 1.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.title_line_2",
    label: "Şifremi Unuttum Başlık Satır 2",
    groupName: "Şifremi Unuttum",
    defaultValue: "e-posta adresini yaz ve",
    description: "Şifremi unuttum başlık satır 2.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.title_line_3",
    label: "Şifremi Unuttum Başlık Satır 3",
    groupName: "Şifremi Unuttum",
    defaultValue: "Şifreni Yenile.",
    description: "Şifremi unuttum başlık satır 3.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.email_label",
    label: "Şifremi Unuttum E-posta Etiketi",
    groupName: "Şifremi Unuttum",
    defaultValue: "E-postan",
    description: "Şifremi unuttum formundaki e-posta etiketi.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.email_placeholder",
    label: "Şifremi Unuttum E-posta Placeholder",
    groupName: "Şifremi Unuttum",
    defaultValue: "ornek@mail.com",
    description: "Şifremi unuttum formundaki e-posta örnek metni.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.error_empty",
    label: "Şifremi Unuttum Boş E-posta Hatası",
    groupName: "Şifremi Unuttum",
    defaultValue: "Şifre sıfırlama bağlantısı için e-posta adresini yazmalısın.",
    description: "Boş e-posta hata mesajı.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.error_send",
    label: "Şifremi Unuttum Gönderim Hatası",
    groupName: "Şifremi Unuttum",
    defaultValue: "Şifre sıfırlama bağlantısı gönderilemedi. E-posta adresini kontrol edip tekrar dene.",
    description: "Reset link gönderim hatası.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.success",
    label: "Şifremi Unuttum Başarı Mesajı",
    groupName: "Şifremi Unuttum",
    defaultValue: "Şifre sıfırlama bağlantısı e-posta adresine gönderildi. Gelen bağlantıdan yeni şifreni oluşturabilirsin.",
    description: "Reset link başarı mesajı.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.button.login",
    label: "Şifremi Unuttum Giriş Butonu",
    groupName: "Şifremi Unuttum",
    defaultValue: "← Giriş",
    description: "Şifremi unuttum sol buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.button.submit",
    label: "Şifremi Unuttum Submit Butonu",
    groupName: "Şifremi Unuttum",
    defaultValue: "Link Gönder",
    description: "Şifremi unuttum submit buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "forgot.button.menu",
    label: "Şifremi Unuttum Menü Butonu",
    groupName: "Şifremi Unuttum",
    defaultValue: "Menü →",
    description: "Şifremi unuttum sağ buton yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.loading_eyebrow",
    label: "Hesabım Yükleme Üst Yazı",
    groupName: "Hesabım",
    defaultValue: "Hesabım",
    description: "Hesabım sayfası yükleme üst yazısı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.loading_title",
    label: "Hesabım Yükleme Başlık",
    groupName: "Hesabım",
    defaultValue: "Bilgiler yükleniyor...",
    description: "Hesabım sayfası yükleme başlığı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.eyebrow",
    label: "Hesabım Üst Yazı",
    groupName: "Hesabım",
    defaultValue: "Kullanıcı paneli",
    description: "Hesabım sayfasındaki küçük üst yazı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.title",
    label: "Hesabım Başlık",
    groupName: "Hesabım",
    defaultValue: "Hesabım",
    description: "Hesabım sayfasındaki ana başlık.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.description",
    label: "Hesabım Açıklama",
    groupName: "Hesabım",
    defaultValue: "Üyelik bilgilerini ve bildirim tercihini buradan takip edebilirsin.",
    description: "Hesabım sayfasındaki açıklama.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.notice",
    label: "Hesabım Bilgi Kutusu",
    groupName: "Hesabım",
    defaultValue: "Profil bilgilerini düzenleyebilir, indirme alanına üyelik panelinden ulaşabilirsin.",
    description: "Hesabım sayfasındaki sarı bilgi kutusu.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.profile_label.full_name",
    label: "Profil Ad Soyad Etiketi",
    groupName: "Hesabım",
    defaultValue: "Ad Soyad",
    description: "Profil kutusundaki ad soyad etiketi.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.profile_label.email",
    label: "Profil E-posta Etiketi",
    groupName: "Hesabım",
    defaultValue: "E-posta",
    description: "Profil kutusundaki e-posta etiketi.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.profile_label.phone",
    label: "Profil Telefon Etiketi",
    groupName: "Hesabım",
    defaultValue: "Telefon",
    description: "Profil kutusundaki telefon etiketi.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.profile_label.notifications",
    label: "Profil Bildirimler Etiketi",
    groupName: "Hesabım",
    defaultValue: "Bildirimler",
    description: "Profil kutusundaki bildirimler etiketi.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.notifications_on",
    label: "Profil Bildirim Açık Metni",
    groupName: "Hesabım",
    defaultValue: "Açık",
    description: "Bildirim açıkken gösterilen metin.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.notifications_off",
    label: "Profil Bildirim Kapalı Metni",
    groupName: "Hesabım",
    defaultValue: "Kapalı",
    description: "Bildirim kapalıyken gösterilen metin.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.button.menu",
    label: "Hesabım Menü Butonu",
    groupName: "Hesabım",
    defaultValue: "← Menü",
    description: "Hesabım sayfası menü butonu.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.button.edit",
    label: "Hesabım Düzenle Butonu",
    groupName: "Hesabım",
    defaultValue: "Düzenle",
    description: "Hesabım sayfası düzenle butonu.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.button.downloads",
    label: "Hesabım İndirilenler Butonu",
    groupName: "Hesabım",
    defaultValue: "İndirilenler",
    description: "Hesabım sayfası indirilenler butonu.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "account.downloads_title",
    label: "Hesabım İndirilenler Tooltip",
    groupName: "Hesabım",
    defaultValue: "İndirilenler alanı yakında aktif olacak.",
    description: "İndirilenler butonunun açıklama metni.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "register.eyebrow",
    label: "Kayıt Üst Yazı",
    groupName: "Kayıt",
    defaultValue: "Üyelik Alanı",
    description: "Kayıt sayfasındaki küçük üst yazı.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "register.title",
    label: "Kayıt Başlık",
    groupName: "Kayıt",
    defaultValue: "Şarkı sözleri ve özel içerikler için Hesap Aç.",
    description: "Kayıt sayfasındaki başlık.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "register.consent_text",
    label: "Kayıt Üyelik Onayı",
    groupName: "Kayıt",
    defaultValue: "Üyelik için bilgilerimin kullanılmasını kabul ediyorum.",
    description: "Kayıt formu üyelik onay metni.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "register.notification_text",
    label: "Kayıt Bildirim Onayı",
    groupName: "Kayıt",
    defaultValue: "Yeni şarkılar ve özel içerikler için bilgilendirme alabilirim.",
    description: "Kayıt formu bildirim onay metni.",
    inputType: "textarea",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "register.button.menu",
    label: "Kayıt Menü Butonu",
    groupName: "Kayıt",
    defaultValue: "← Menü",
    description: "Kayıt sayfası menü butonu.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "register.button.submit",
    label: "Kayıt Oluştur Butonu",
    groupName: "Kayıt",
    defaultValue: "Oluştur",
    description: "Kayıt formu submit butonu.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "register.button.login",
    label: "Kayıt Giriş Butonu",
    groupName: "Kayıt",
    defaultValue: "Giriş →",
    description: "Kayıt sayfası giriş butonu.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "footer.copyright",
    label: "Footer Telif Metni",
    groupName: "Footer",
    defaultValue: "© 2026 Muhammed Tankılıç. Tüm hakları saklıdır.",
    description: "Genel footer telif metni.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "footer.credit",
    label: "Footer Tasarım Kredisi",
    groupName: "Footer",
    defaultValue: "resultankilic.ai tarafından tasarlanmıştır",
    description: "Genel footer tasarım kredisi.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  },
  {
    key: "footer.about_note",
    label: "Hakkında Footer Notu",
    groupName: "Footer",
    defaultValue: "Hakkında · Bestelerim · Coverlarım",
    description: "Hakkında sayfası footer sağ metni.",
    inputType: "text",
    hiddenInBulkEditor: false,
    isPublic: true,
  }
] satisfies SiteTextDefinition[];

export const editableSiteTextDefinitions = siteTextDefinitions.filter(
  (definition) => !definition.hiddenInBulkEditor,
);

export const siteTextGroups = Array.from(
  new Set(editableSiteTextDefinitions.map((definition) => definition.groupName)),
);

export const siteTextKeys = siteTextDefinitions.map((definition) => definition.key);

export function getSiteTextDefault(key: string) {
  return (
    siteTextDefinitions.find((definition) => definition.key === key)
      ?.defaultValue ?? ""
  );
}

export function getSiteTextDefinition(key: string) {
  return siteTextDefinitions.find((definition) => definition.key === key);
}

export function createDefaultSiteTextMap() {
  return siteTextDefinitions.reduce<Record<string, string>>((acc, definition) => {
    acc[definition.key] = definition.defaultValue;
    return acc;
  }, {});
}

export function mergeSiteTextRows(
  rows: Array<{ key: string; value: string | null }>,
) {
  const settings = createDefaultSiteTextMap();

  for (const row of rows) {
    settings[row.key] = row.value ?? "";
  }

  return settings;
}
